// feed-loader.ts — progressively loads/renders person cards via IntersectionObserver.
// Card HTML is generated by person-renderer.ts (shared with PersonCard.astro).
import { esc, renderPersonCard, dateHeader, type PersonEvent } from './person-renderer';
export { esc, dateHeader };

const BASE = (document.documentElement.dataset.base ?? '/people-website').replace(/\/$/, '');
const DATA_URL = `${BASE}/data/changelog.json`;
const BATCH_SIZE = 50;

// renderCard re-exports renderPersonCard for backward compatibility.
export function renderCard(e: PersonEvent, landscapeLogos: Record<string, string>): string {
  return renderPersonCard(e, landscapeLogos);
}
export async function initFeedLoader(staticCount: number, landscapeLogos: Record<string, string>, onBatchLoaded?: () => void) {
  const feed = document.getElementById('timeline-feed');
  if (!feed) return;
  let allEvents: PersonEvent[] = [], nextIdx = staticCount, loading = false, done = false;
  function appendBatch() {
    if (loading || done) return;
    loading = true;
    const batch = allEvents.slice(nextIdx, nextIdx + BATCH_SIZE);
    nextIdx += batch.length;
    done = nextIdx >= allEvents.length;
    for (const e of batch) {
      const header = dateHeader(e.timestamp);
      let group = feed.querySelector<HTMLElement>(`.day-group[data-date="${CSS.escape(header)}"]`);
      if (!group) {
        group = document.createElement('section');
        group.className = 'day-group';
        group.dataset.date = header;
        group.innerHTML = `<h2 class="day-header">${esc(header)}</h2>`;
        feed.insertBefore(group, sentinel);
      }
      group.insertAdjacentHTML('beforeend', renderCard(e, landscapeLogos));
    }
    loading = false;
    onBatchLoaded?.();
    if (done) observer.disconnect();
  }
  const sentinel = document.createElement('div');
  sentinel.id = 'feed-sentinel'; feed.appendChild(sentinel);
  const res = await fetch(DATA_URL);
  allEvents = await res.json() as Event[];
  done = nextIdx >= allEvents.length;
  const observer = new IntersectionObserver((entries) => {
    if (entries[0].isIntersecting) appendBatch();
  }, { rootMargin: '400px' });
  observer.observe(sentinel);
  appendBatch();
}
